### ISSUE TITLE
Social Icon missing

### ISSUE THREAD

**Issue by GenXclub** [Accipiters/GenXclub.github.io#2]
### Issue -  Soical Icon missing

**To do**
Provide links to join the below platforms.
- [x] WhatsApp - https://chat.whatsapp.com/JXlW1620Z42ImP0mpxZZ5y
- [x] Telegram - https://t.me/genXclub

Links attached.

**Comment by StealthAdder** [comment]
@GenXclub Pull master and the site is fired up.
